workflows:
  version: 2
  build:
    jobs:
      run-tests:
        docker:
            - image: circleci/python:3.6.8
        working_directory: ~/usefulCommands
        steps:
            - checkout
            - run: pip install --user --upgrade pip
            - run: pip install pytest

    
            
