
version: 2
jobs:
    run-tests:
        docker:
            - image: circleci/python:3.6.8
        working_directory: ~/usefulCommands
        steps:
            - checkout
            - run: pip install --user --upgrade pip
            - run: pip install pytest
            
workflows:
  version: 2
  test-publish-image:
    jobs:
      - docker-image:
          context: org-global
          requires:
            - run-tests
      - run-tests:
          context: org-global