version: 2

jobs:
  test:
    docker:
        - image: circleci/python:3.6.8
    working_directory: ~/usefulCommands
    steps:
        - checkout
        - run: pip install --user --upgrade pip   
        - run: pip install --user pytest
        - run: python -m pytest
        
workflows:
  version: 2
  test:
    jobs:
      - test
